name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORG_KEY: ${{ secrets.SONAR_ORG_KEY }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'

    # Install Mosquitto and start the broker
    - name: Install and start Mosquitto
      run: |
        sudo apt-get update
        sudo apt-get install -y mosquitto mosquitto-clients
        sudo service mosquitto start
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Build LoggingService
    - name: Build LoggingService
      run: |
        dotnet restore
        dotnet build --configuration ${{ matrix.configuration }}
        mkdir -p LoggingServiceArtifact
        cp -r LoggingService/bin/${{ matrix.configuration }}/* LoggingServiceArtifact/
      working-directory: ${{ github.workspace }}

    # Publish the LoggingService artifact
    - name: Publish LoggingService Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LoggingService
        path: LoggingServiceArtifact

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Setup Java 17 for Static Analysis
    - name: Download Java 17
      run: |
        wget https://download.java.net/java/GA/jdk17.0.2/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
        tar -xvf openjdk-17.0.2_linux-x64_bin.tar.gz

    - name: Move Java 17 to /usr/lib/jvm
      run: |
        sudo mkdir -p /usr/lib/jvm
        sudo mv jdk-17.0.2 /usr/lib/jvm/

    - name: Set JAVA_HOME and PATH
      run: |
        echo "export JAVA_HOME=/usr/lib/jvm/jdk-17.0.2" >> $GITHUB_ENV
        echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

    - name: Update alternatives
      run: |
        sudo update-alternatives --install /usr/bin/java java $JAVA_HOME/bin/java 1
        sudo update-alternatives --set java $JAVA_HOME/bin/java

    - name: Verify Java version
      run: java -version

    # Static Analysis
    - name: Run static analysis with SonarCloud
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /k:"${{ env.SONAR_PROJECT_KEY }}" /d:sonar.host.url="${{ env.SONAR_HOST_URL }}" /d:sonar.login="${{ env.SONAR_TOKEN }}" /o:"${{ env.SONAR_ORG_KEY }}"
        dotnet build
        dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"
